### PR TITLE
Scrutineering Revamp F22

### PR DESCRIPTION
**Pull request by pramukap**
# Quality Assurance Checklist
To make reviews more efficient, please make sure the board meets the following standards and check everything off once the board meets the quality check. Once everything has been checked, the assigned reviewers will begin the review process. _Edit this description to check off the list._

There are exceptions with all guidelines. As long as your decisions are justified, then you are good! Contact the reviewers or the leads about any exceptions.

### Minimum Prerequisites
- [X] Pushed changes to branch.
- [x] The board passes ERC and DRC.
    - Note some ERC warnings are acceptable.
- [x] All traces are routed.
- [x] Units are in metric.

### 2D Spacing
- [x] The components are spaced out at an optimal distance.
    - All components can be easily hand-soldered.
    - IPC-SM-782A Standard requires a minimum distance of 1.0mm from edge to edge.
- [x] Components that are in parallel with each other are spaced out at an equal distance when possible.
- [x] The components are aligned with each other when possible.
- [x] Components are grouped based off of functionality.
    - E.g. all components for CAN should be grouped.
- [x] Bypass capacitors are less than 1cm away from their respective IC's power pins.

### 3D Spacing
- [x] Layout of components have been placed with mounting location and usage of the board in mind.
    - Are PCBs going to be stacked on above/below this board? Are tall components placed accordingly?
    - Are buttons and lights easily accessible and viewable?
    - When mounted into the car, are the heights of the components and connectors accounted for?
- [x] Location of connectors and wires going out of the board will prevent messy wiring.
    - Are all the wires that are going in the same direction placed on the same edge of the board?

### Components
- [x] Custom footprints have been double checked with the datasheet.
- [x] Pin 1 of the footprint is labeled in some way.

### Copper Layer
- [x] The trace widths and trace clearances are greater than JLCPCB's minimum requirements.
- [x] The trace lengths are as short as possible.
    - Can there be a more optimal route if you go to another layer?
- [x] Each trace's width is capable of handling the expected current flow.
    - Use PCB width calculator to calculate trace width.
- [x] *No sharp corners. No trace angles equal to or less than 90 degrees.
- [x] Traces are in parallel with each other when possible.
    - E.g. traces connected between an IC and MCU can be placed in parallel with each other.
- [x] There are no random trace appendages.
- [x] Vias placed in copper pads are fully encompassed in the copper pads.
- [x] Through-hole components do not have extraneous vias.

*Not really a problem for modern manufacturing techniques but good practice and important for high speed signal integrity.

### Silkscreen Layer
- [x] Visible text sizes are greater than JLCPCB's minimum requirements.
- [x] All visible text is on the silkscreen layer.
- [x] All reference labels of each component are not overlapping a copper pad or another component.
- [x] All connector pins are labeled with a meaningful and helpful name.
- [x] All LEDs are labeled with a meaningful and helpful name.

### Edge Cut Layer
- [x] The dimensions of the board and the mounting holes are nice values in metric i.e. no long decimals.
- [x] The physical outline of the board is on the edge cut layer.
- [x] Edge cuts are straight and parallel with opposite edge of the board.
- [x] Mounting holes are aligned.
- [x] Corners are curved and contoured to mounting holes.

### IMPORTANT NOTICE
- [x] I am confident that this board will be safe to use in a safety critical environment.
- [x] I had fun :)

## Other Comments
_Write any comments about the board that would help the reviewers here._

### CODE REVIEW

**Comment by manthanand** [comment]
On the schematic, write down which side is the battery side and which side is the Minions side.

**Comment by HannahSLee14** [comment]
Overall, I think this looks great! I just have one question - were we still thinking of adding some kind of indicator to show that the battery module and minion board sides are connected? 

Great work so far though!

**Review by tasniabari — APPROVED** [review]
Good job with layout and traces. Only concern is the silkscreen warning on the ERC, which you've accounted for.

**Review by ray4477 — APPROVED** [review]
Looks good to me. The only thing I would suggest is modeling the actual board with the step files with the THT through-hole test points and confirm with electromechanical that there's enough space to test between each test point.

**Review by connorl309 — APPROVED** [review]
Board looks good, design choices make sense. Spoke w Pramuka while reviewing it and didn't see anything wrong.

**Review by MichaelMohn — APPROVED** [review]
Board looks legit to me.

**Comment by HannahSLee14** [comment]
It's looking great! A few comments/questions:
- Is the DIP switches the same one that we used before? If it is, then one problem we faced earlier was that the footprint on KICAD was slightly too small (I'm sorry I didn't catch this earlier)
- How are we planning on using this for scrutineering? This [link](https://www.americansolarchallenge.org/ASC/wp-content/uploads/2015/02/ASC2016_Protection-System-Test-Procedure.pdf) gives us a description of the BPS Test procedure, so we are expecting to be able to test for over-voltage, under-voltage, over-current, and over-temperature. How are we planning on simulating each of these conditions?
- Where are we planning on putting this? Are we planning on keeping it permanently in the BPS part of the battery box?

**Comment by manthanand** [comment]
1. dip switches are changed
2. we are just testing voltage with this so it will be used in the same way as the previous scrutineeering PCB (just using test points to hold alligator clips instead of banana plugs).
3. This is going to be permanently in the battery box.

**Pull request merged**
